### PR TITLE
1.18.2 support

### PR DESCRIPTION
**Pull request by LifeIsAParadox**
I have add support for 1.18.2. And i have fixed deprecated stuff

### CODE REVIEW

**Comment by Sintinium** [comment]
Thanks! I'll try to get this released in a couple of days

**Comment by alext** [comment]
Any update on this?  It would be good to be able to use this with 1.18.2.

thanks.

**Comment by Sintinium** [comment]
Sorry I've been dealing with medical issues and it's hard to find the motivation to keep up atm. I'll try to have it released as soon as I can

**Comment by alext** [comment]
Sorry to hear about your medical issues. I hope they're resolved soon.

Thanks for releasing this, and thanks for making this mod.

**Pull request merged**
